### ISSUE TITLE
File name is case sensitive on Linux

### ISSUE THREAD

**Issue by JorisGoosen** [sophieberkhout/JASP-metaBMA#1]
https://github.com/sophieberkhout/JASP-metaBMA/blob/3fa739a22a3940f86af27ef6fc3bd5164b8c2a3f/inst/description.json#L21

Hey I was looking at your code for issue https://github.com/jasp-stats/INTERNAL-jasp/issues/342 and noticed that I couldn't open your QML because you wrote `"qml":      "BayesianMetaAnalysis.qml"` and it should be exactly equal to the actual filename so: `"qml":      "bayesianMetaAnalysis.qml"`

**Comment by sophieberkhout** [comment]
Oops I totally missed this! I changed it now.
